modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/sugardog125/Wasabi/issues"
license = "All Rights Reserved"

[[mods]]
modId = "wasabi"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:bamboo"
authors = "sugardog125"
credits = ""
displayName = "Wasabi"
description = '''
    This mod forced vannila like Japanese stuff!
'''

[[dependencies.wasabi]]
    modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
    side = "BOTH"

[[dependencies.wasabi]]
    modId = "forge"
mandatory = true
versionRange = "[37.0.21,)"
ordering = "NONE"
    side = "BOTH"