modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/template-mod/issues"
license = "https://github.com/team-abnormals/template-mod/blob/main/LICENSE.txt"

[[mods]]
modId = "wasabi"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
authors = "bagu_chan"
credits = ""
displayName = "Wasabi"
description = '''
    This mod forced vannila like Japanese stuff!
    '''

[[dependencies.wasabi]]
    modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
    side = "BOTH"

[[dependencies.wasabi]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"